"""Declarative base and column conventions shared by every model."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, MetaData, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention so that autogenerated constraint names are stable
# and a migration's DROP matches the CREATE that produced it.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def pk() -> Mapped[int]:
    """Identity primary key. BIGINT throughout: Readings alone exceed INT."""
    return mapped_column(BigInteger, primary_key=True, autoincrement=True)


def created_at() -> Mapped[datetime]:
    return mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
